// Para requisições com body:
// Content-Type: application/json 
// Pule 1 linha
// {}

// Para requisições com headers: 
// Authorization: "token"

###
POST http://localhost:3003/user
Content-Type: application/json 

{
    "name": "Keianne Zaze",
    "nickname": "Kei",
    "email": "keianne@zaze.ped.br"
}

###
GET http://localhost:3003/user/2