// Para requisições com body:
// Content-Type: application/json 
// Pule 1 linha
// {}

// Para requisições com headers: 
// Authorization: "token"

###
POST http://localhost:3003/user
Content-Type: application/json 

{
    "name": "Adriano Nunes",
    "nickname": "Branco",
    "email": "adriano@adriano.uk"
}